#!/usr/bin/env bash
## START STANDARD SITE BUILD SCRIPT INCLUDE
readonly THIS_SCRIPT="$(readlink -f "${BASH_SOURCE[0]}")"
readonly BOOTSTRAP="$(dirname "$THIS_SCRIPT")/resources/bootstrap.inc.sh"
readonly BOOTSTRAP_VERSION=v1.0.13
if ! [ -f "$BOOTSTRAP" ] || ! source "$BOOTSTRAP"; then
  curl -H "Cache-Control: no-cache" --fail --silent --show-error -w "curl: Finished attempt to download %{url}" "https://raw.githubusercontent.com/keymanapp/shared-sites/$BOOTSTRAP_VERSION/bootstrap.inc.sh" -o "$BOOTSTRAP.tmp" || exit 1
  source "$BOOTSTRAP.tmp"
  rm -f "$BOOTSTRAP.tmp"
fi
## END STANDARD SITE BUILD SCRIPT INCLUDE

readonly KEYMAN_CONTAINER_NAME=keyman-website
readonly KEYMAN_CONTAINER_DESC=keyman-com-app
readonly KEYMAN_IMAGE_NAME=keyman-website
readonly HOST_KEYMAN_COM=keyman.com.localhost

source _common/keyman-local-ports.inc.sh
source _common/docker.inc.sh

################################ Main script ################################

builder_describe \
  "Setup keyman.com site to run via Docker." \
  configure \
  clean \
  build \
  start \
  stop \
  test \
  htaccess "rebuild .htaccess from .htaccess.in (for development)"

builder_parse "$@"

function preprocess_htaccess() {
  echo "# DO NOT EDIT THIS FILE -- EDIT .htaccess.in" > .htaccess
  # assuming format of relevant lines in locales.json to be "tag": "name"
  local locales localesregex
  locales=($(cat ./_includes/locale/locales.json | grep '"' | cut -d\" -f 2 -))
  localesregex=$(IFS=\| ; echo "${locales[*]}")
  sed -e "s/@locales/${localesregex}/g" .htaccess.in >> .htaccess
}

function do_configure() {
  preprocess_htaccess
  bootstrap_configure
}

function do_start() {
  # for developer convenience, rebuild .htaccess when starting container
  preprocess_htaccess
  start_docker_container $KEYMAN_IMAGE_NAME $KEYMAN_CONTAINER_NAME $KEYMAN_CONTAINER_DESC $HOST_KEYMAN_COM $PORT_KEYMAN_COM $BUILDER_CONFIGURATION
}

source resources/commands.inc.sh

function test_docker_container() {
  local LINK_RESULT
  echo "TIER_TEST" > tier.txt

  # from commands.inc.sh

  do_test_record_start_time

  builder_echo blue "---- PHP unit tests"
  do_test_unit_tests "${KEYMAN_CONTAINER_DESC}"

  builder_echo blue "---- Lint PHP files"
  do_test_lint "${KEYMAN_CONTAINER_DESC}"

  builder_echo blue "---- Testing links"
  LINK_RESULT=0
  do_test_links "http://localhost:${PORT_KEYMAN_COM}" || LINK_RESULT=$?
  builder_echo blue "Done checking links; linkinator exit code: ${LINK_RESULT}"
  do_test_print_link_report

  do_test_print_container_error_logs "${KEYMAN_CONTAINER_DESC}"

  rm tier.txt
  return "$LINK_RESULT"
}

builder_run_action configure  do_configure
builder_run_action clean      clean_docker_container $KEYMAN_IMAGE_NAME $KEYMAN_CONTAINER_NAME
builder_run_action stop       stop_docker_container  $KEYMAN_IMAGE_NAME $KEYMAN_CONTAINER_NAME
builder_run_action build      build_docker_container $KEYMAN_IMAGE_NAME $KEYMAN_CONTAINER_NAME $BUILDER_CONFIGURATION
builder_run_action start      do_start

builder_run_action test       test_docker_container
builder_run_action htaccess   preprocess_htaccess
