#!/usr/bin/env bash
## START STANDARD SITE BUILD SCRIPT INCLUDE
readonly THIS_SCRIPT="$(readlink -f "${BASH_SOURCE[0]}")"
readonly BOOTSTRAP="$(dirname "$THIS_SCRIPT")/resources/bootstrap.inc.sh"
readonly BOOTSTRAP_VERSION=v1.0.11
if ! [ -f "$BOOTSTRAP" ] || ! source "$BOOTSTRAP"; then
  curl -H "Cache-Control: no-cache" --fail --silent --show-error -w "curl: Finished attempt to download %{url}" "https://raw.githubusercontent.com/keymanapp/shared-sites/$BOOTSTRAP_VERSION/bootstrap.inc.sh" -o "$BOOTSTRAP.tmp" || exit 1
  source "$BOOTSTRAP.tmp"
  rm -f "$BOOTSTRAP.tmp"
fi
## END STANDARD SITE BUILD SCRIPT INCLUDE

readonly KEYMAN_CONTAINER_NAME=keyman-website
readonly KEYMAN_CONTAINER_DESC=keyman-com-app
readonly KEYMAN_IMAGE_NAME=keyman-website
readonly HOST_KEYMAN_COM=keyman.com.localhost

source _common/keyman-local-ports.inc.sh
source _common/docker.inc.sh

################################ Main script ################################

builder_describe \
  "Setup keyman.com site to run via Docker." \
  configure \
  clean \
  build \
  start \
  stop \
  test \
  htaccess "rebuild .htaccess from .htaccess.in (for development)"

builder_parse "$@"

function preprocess_htaccess() {
  echo "# DO NOT EDIT THIS FILE -- EDIT .htaccess.in" > .htaccess
  # assuming format of relevant lines in locales.json to be "tag": "name"
  local locales localesregex
  locales=($(cat ./_includes/locale/locales.json | grep '"' | cut -d\" -f 2 -))
  localesregex=$(IFS=\| ; echo "${locales[*]}")
  sed -e "s/(@locales)/(([a-z]{2,3})(-([A-Z][a-z]{3}))?(-([A-Z]{2}|[0-9]{3}))?)/g" .htaccess.in >> .htaccess
}

function do_configure() {
  preprocess_htaccess
  bootstrap_configure
}

function do_start() {
  # for developer convenience, rebuild .htaccess when starting container
  preprocess_htaccess
  start_docker_container $KEYMAN_IMAGE_NAME $KEYMAN_CONTAINER_NAME $KEYMAN_CONTAINER_DESC $HOST_KEYMAN_COM $PORT_KEYMAN_COM $BUILDER_CONFIGURATION
}

function test_docker_container() {
  # Note: ci.yml replicates these

  echo "TIER_TEST" > tier.txt
  set +e;
  set +o pipefail;

  builder_echo blue "---- PHP unit tests"
  docker exec $KEYMAN_CONTAINER_DESC sh -c "vendor/bin/phpunit --testdox"

  # Lint .php files for obvious errors
  builder_echo blue "---- Lint PHP files"
  docker exec $KEYMAN_CONTAINER_DESC sh -c "find . -name '*.php' | grep -v '/vendor/' | xargs -n 1 -d '\\n' php -l"

  # NOTE: link checker runs on host rather than in docker image
  builder_echo blue "---- Testing links"

  # determine non-en locales to ignore along with /downloads/releases
  readarray -t ignoresArray <<< $(find ./_includes/locale/strings/keyboards/ -maxdepth 1 -name '*.php' ! -name "en.php" \
    -execdir basename  {} .php ';')
  local baseURL="http://localhost:8053"
  local ignoreStr=("  --exclude ${baseURL}*/downloads/releases/*")
  for locale in "${ignoresArray[@]}"; do
    ignoreStr+=" --exclude ${baseURL}/${locale}/*"
  done
  echo "ignoreStr: ${ignoreStr[@]}"
  npx broken-link-checker ${baseURL}/_test --recursive --ordered ---host-requests 50 -e --filter-level 3 ${ignoreStr} | tee blc.log
  local BLC_RESULT=${PIPESTATUS[0]}
  echo ----------------------------------------------------------------------
  echo Link check summary
  echo ----------------------------------------------------------------------
  cat blc.log | \
    grep -E "BROKEN|Getting links from" | \
    grep -B 1 "BROKEN";

  builder_echo blue "Done checking links"
  rm tier.txt
  return "${BLC_RESULT}"
}

builder_run_action configure  do_configure
builder_run_action clean      clean_docker_container $KEYMAN_IMAGE_NAME $KEYMAN_CONTAINER_NAME
builder_run_action stop       stop_docker_container  $KEYMAN_IMAGE_NAME $KEYMAN_CONTAINER_NAME
builder_run_action build      build_docker_container $KEYMAN_IMAGE_NAME $KEYMAN_CONTAINER_NAME $BUILDER_CONFIGURATION
builder_run_action start      do_start

builder_run_action test       test_docker_container
builder_run_action htaccess   preprocess_htaccess
