name: Add new issues and pull requests to projects

on:
  pull_request:
    types:
      - opened
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add new issues and pull requests to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/keymanapp/projects/1
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
