name: CI

on:
  [pull_request]
jobs:

  build-test:
    runs-on: ubuntu-latest
    env:
      KEYMANHOSTS_TIER: TIER_TEST
      KEYMAN_CONTAINER_DESC: keyman-com-app

    steps:
    - name: Checkout
      uses: actions/checkout@v6.0.2

    - name: Build the docker image for keyman.com app
      shell: bash
      run: |
        echo "TIER_TEST" > tier.txt
        ./build.sh configure build start --debug
      env:
        fail-fast: true

    #
    # Finally, run the tests
    #
    - name: Test setup
      shell: bash
      run: |
        source ./resources/commands.inc.sh
        set -e
        do_test_record_start_time

    - name: PHP test
      shell: bash
      run: |
        source ./resources/commands.inc.sh
        set -e
        STEP_RESULT=0
        do_test_unit_tests "$KEYMAN_CONTAINER_DESC" || STEP_RESULT=$?
        echo "Unit test result: ${STEP_RESULT}"
        echo "TEST_START_TIME=${TEST_START_TIME}" >> "$GITHUB_ENV"
        echo "TEST_RESULT=${STEP_RESULT}" >> "$GITHUB_ENV"

    - name: Lint
      shell: bash
      run: |
        source ./resources/commands.inc.sh
        set -e
        STEP_RESULT=0
        do_test_lint "$KEYMAN_CONTAINER_DESC" || STEP_RESULT=$?
        TEST_RESULT=$(( $STEP_RESULT || $TEST_RESULT ))
        echo "Lint result: ${STEP_RESULT}"
        echo "TEST_RESULT=${TEST_RESULT}" >> "$GITHUB_ENV"

    - name: Check broken links
      shell: bash
      continue-on-error: false
      run: |
        source ./resources/commands.inc.sh
        set -e
        STEP_RESULT=0
        do_test_links "http://localhost:8053" || STEP_RESULT=$?
        TEST_RESULT=$(( $STEP_RESULT || $TEST_RESULT ))
        echo "Link check result: ${STEP_RESULT}"
        echo "TEST_RESULT=${TEST_RESULT}" >> "$GITHUB_ENV"

      # We split the reporting of errors into a separate step for ease of viewing

    - name: Report on broken links
      run: |
        source ./resources/commands.inc.sh
        set -e
        STEP_RESULT=0
        do_test_print_link_report || STEP_RESULT=$?
        TEST_RESULT=$(( $STEP_RESULT || $TEST_RESULT ))
        echo "Link report result: ${STEP_RESULT}"
        echo "TEST_RESULT=${TEST_RESULT}" >> "$GITHUB_ENV"

    - name: Check PHP errors
      shell: bash
      run: |
        source ./resources/commands.inc.sh
        set -e
        do_test_print_container_error_logs "$KEYMAN_CONTAINER_DESC" || LINK_RESULT=$?
        exit "${TEST_RESULT}"
